apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-express
spec:
  selector:
    matchLabels:
      app: app-express
  template:
    metadata:
      labels:
        app: app-express
    spec:
      containers:
      - name: app-express
        image: app-express
        ports:
        - containerPort: 3000
