apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: app-express
  newName: rubemnascimento81/app-express
  newTag: 70ff47e243c473f80addfd9fe2cb7076a41fd83b
